###**Problem Statement**:
A movie review site needs to create a database to store their data and perform operations on it. You are asked to create a dummy model with 100 users and 1000 movies to explain how it will work

###Tasks to be performed:
1. Generate 1000 movie IDs starting from 1301

2. Create a matrix, movies_matrix, to store users rating such that
>There are 100 users

>Each user can review as many movies as he/she wants

>The review should be in between 0 to 10 (both inclusive)

3. We have ten movie experts, let us take their reviews also. Also, 50 new movies have to be added and their reviews

4. Create, final_movie_rating matrix with four columns i.e., ‘Movie ID’, ‘Average rating’, ‘Number of ratings’, and ‘Standard deviation of ratings’

5. Also convert the final movie ratings to have range from 0 to 10, such that the minimum rating converts to 0 and maximum to 10, and the other values in between

6. Display the films rating-wise, highest to lowest

In [2]:
import numpy as np

###Task 1: Create a NumPy array of 1000 movie IDs starting from 1301

In [3]:
movie_id = np.arange(1301,2301)
print(movie_id[:15])
movie_id.size

[1301 1302 1303 1304 1305 1306 1307 1308 1309 1310 1311 1312 1313 1314
 1315]


1000

In [4]:
user_id = []
for i in range(20201,20301):
  user_id.append(i)
user_id = np.array(user_id)
print(user_id[:15])
user_id.size #checking the number of elements in numpy array

[20201 20202 20203 20204 20205 20206 20207 20208 20209 20210 20211 20212
 20213 20214 20215]


100

###Task 2: Create Matrix 1 such that:
>* There are 100 users
>* Each user can review as many movies as he/she wants.
>* The review should be in between 0 to 10 (both inclusive)
>* The movies which are not reviewed by a user should have value -1

In [5]:
def createMovieMatrix(numUsers, numMovies):
  import random
  movie_matrix = []
  for user in range(numUsers):
      movies_rated_by_a_user = np.full(numMovies, -1)#number of movies rated intitally all -1
      #print(movies_rated_by_a_user)
      num_movies_rated = random.randint(0, numMovies -1)# which all movies rated by me
      #print('number of movies rated by this user: ', num_movies_rated)
      movies_that_user_rate = random.sample(range(numMovies), num_movies_rated)
      #print('movies that this user rated: ' , movies_that_user_rate)
      for i in movies_that_user_rate:
        #user rating for movies they chosed to rate
        movies_rated_by_a_user[i] = random.randint(0, 10)
        #print('random ratings of the this user:',movies_rated_by_a_user )
      movie_matrix.append(movies_rated_by_a_user)
  movie_matrix = np.array(movie_matrix)
  return movie_matrix


In [6]:
user_materix = createMovieMatrix(100,1000)
print('Movie Matrix details:')
print('shape:' , user_materix.shape)
print('type:', type(user_materix))
print('10:10 slice of movie_matrix', '\n', user_materix[0:11,:11])

Movie Matrix details:
shape: (100, 1000)
type: <class 'numpy.ndarray'>
10:10 slice of movie_matrix 
 [[-1 -1  8 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  9 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1  9 -1 -1  2  5 -1 -1  2 -1]
 [ 5  3  8  4 10  0  4  9  0  9  8]
 [-1  6  8 -1  7  2 -1  7  0 -1  8]
 [ 7 -1  9  5  2  8  1  7  4 -1  6]
 [ 0 -1 -1 -1 -1 -1 -1  7 -1 -1 -1]
 [10  8  5  2 10  5 -1 10  8  4  9]
 [-1  3 -1  9 -1 -1 -1 -1  2 -1 -1]
 [-1 -1 -1 -1 -1 -1  3 -1 -1 -1 -1]]


###Task 2: Create Matrix 10 for Expert Reviews and 50 new movies

In [7]:
#adding 10 new expertsnreviews
expert_matrix = createMovieMatrix(10,1000)
print('shape:' , expert_matrix.shape)
print('type:', type(expert_matrix))
print('10,10 slice of movie_matrix', '\n', expert_matrix[0:10,:10])

shape: (10, 1000)
type: <class 'numpy.ndarray'>
10,10 slice of movie_matrix 
 [[-1  5  0  1  2 10  1  6  2 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  8  6 -1  0  1 -1 -1  0 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 4  3  3  4 -1  3  7  7  5  4]
 [-1  4  5 -1 -1 -1 -1 -1 -1 -1]
 [ 9  7  7  4 -1  6  8  9  7 10]
 [-1  1  2 -1 -1 -1 -1  5 -1  2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  9 10 -1 -1 -1  6  6 -1 -1]]


In [8]:
#adding 50 new movies
new_movie_matrix = createMovieMatrix(110,50)
print('shape:' , new_movie_matrix)
print('type:', type(new_movie_matrix))
print('10,10 slice of movie_matrix', '\n', new_movie_matrix[0:10,:10])

shape: [[ 5 10  0 ... -1  8 -1]
 [ 9  3 -1 ...  0  2  6]
 [-1 -1 -1 ... -1 -1  9]
 ...
 [10 -1 -1 ...  0  1  2]
 [ 5 -1 -1 ...  7  2 -1]
 [-1 -1 -1 ... -1 -1  4]]
type: <class 'numpy.ndarray'>
10,10 slice of movie_matrix 
 [[ 5 10  0  8  8 -1  3 -1 -1  2]
 [ 9  3 -1  9  0 10  1  9  3  9]
 [-1 -1 -1 -1  8 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  2 -1  5 -1 -1 -1  8 -1 -1]
 [-1 -1 10 -1 -1  6 -1  7  2  1]
 [ 9  7 10 -1  8  8 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 5  5  9  1  5  2  0  1  9 -1]]


###Stacking user movie matrix and expert movie matrix as a final matrix

In [9]:
finale_movie_matrix = np.vstack([user_materix, expert_matrix])
print('shape:' , finale_movie_matrix.shape, '\n', expert_matrix.shape, '\n', user_materix.shape )
print('type:', type(finale_movie_matrix))

shape: (110, 1000) 
 (10, 1000) 
 (100, 1000)
type: <class 'numpy.ndarray'>


In [10]:
finale_movie_matrix1 = np.hstack([finale_movie_matrix, new_movie_matrix])
print('shape:' , finale_movie_matrix.shape, '\n', new_movie_matrix.shape, '\n', finale_movie_matrix1.shape )

shape: (110, 1000) 
 (110, 50) 
 (110, 1050)


####**final_movie_rating matrix** with four columns i.e., ‘Movie ID’, ‘Average rating’, ‘Number of ratings’, and ‘Standard deviation of ratings’

In [11]:
print(finale_movie_matrix1.shape[1])

1050


In [12]:
movie_id = np.arange(1301,2351)
movie_stats = []
for i in range(finale_movie_matrix1.shape[1]):
  m = finale_movie_matrix1[:,i]
  m = m[m >=0]
  movie_stats.append([movie_id[i],m.mean(),m.size,m.std()])
movie_stats = np.array(movie_stats)
movie_stats = np.round(movie_stats,2)

**Comment:**

**m = m[m >=0]**

Condition m >= 0: This creates a boolean array of the same shape as m. Each element in this boolean array is True if the corresponding element in m is greater than or equal to 0, and False otherwise.

For example, if m is [2.5, -1.0, 4.0, -0.5], then m >= 0 evaluates to [True, False, True, False].
Indexing m[m >= 0]: This uses boolean indexing to filter m. It selects only the elements where the corresponding boolean value is True.

Continuing with the example, applying this filter to m would result in [2.5, 4.0], as only these elements are greater than or equal to 0

In [13]:
print(movie_stats)
print(type(movie_stats),movie_stats.shape)

[[1301.      4.8    51.      3.4 ]
 [1302.      5.36   59.      3.29]
 [1303.      4.9    61.      3.03]
 ...
 [2348.      5.16   43.      3.19]
 [2349.      4.66   50.      2.84]
 [2350.      6.08   53.      3.25]]
<class 'numpy.ndarray'> (1050, 4)


#5. Converting the final movie ratings to have range from 0 to 10, such that the minimum rating converts to 0 and maximum to 10, and the other values in between

In [24]:
#Converting the average of movie ratings to have the range 0 to 10
x = movie_stats[:,1]
old_range = x.max()-x.min()
new_range = (10 - 0)
movie_stats[:,1] = ((x - x.min())*(new_range/old_range) + 0)

In [25]:
movie_stats[:,1]

array([4.39688716, 6.57587549, 4.78599222, ..., 5.79766537, 3.85214008,
       9.37743191])

In [27]:
movie_stats.shape

(1050, 4)

In [31]:
sorted_films = movie_stats[movie_stats[:,1].argsort()[::-1]]

In [32]:
print(sorted_films)

[[2.08700000e+03 1.00000000e+01 5.50000000e+01 2.94000000e+00]
 [1.41900000e+03 9.57198444e+00 5.30000000e+01 3.03000000e+00]
 [2.35000000e+03 9.37743191e+00 5.30000000e+01 3.25000000e+00]
 ...
 [1.31200000e+03 7.00389105e-01 6.80000000e+01 2.89000000e+00]
 [2.20200000e+03 7.78210117e-02 5.40000000e+01 3.13000000e+00]
 [1.53100000e+03 0.00000000e+00 5.20000000e+01 3.04000000e+00]]


argsort() = it shows the sorted indexes of the array.


##Save as csv file and read array from a csv file

In [33]:
np.savetxt('ranked_movie_data.csv',sorted_films, delimiter=',', fmt='%.2f')

In [34]:
data = np.genfromtxt('ranked_movie_data.csv', delimiter = ',')

In [35]:
data

array([[2.087e+03, 1.000e+01, 5.500e+01, 2.940e+00],
       [1.419e+03, 9.570e+00, 5.300e+01, 3.030e+00],
       [2.350e+03, 9.380e+00, 5.300e+01, 3.250e+00],
       ...,
       [1.312e+03, 7.000e-01, 6.800e+01, 2.890e+00],
       [2.202e+03, 8.000e-02, 5.400e+01, 3.130e+00],
       [1.531e+03, 0.000e+00, 5.200e+01, 3.040e+00]])